using Schrabber.Interfaces;
using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel;
using System.Globalization;
using System.Linq;
using System.Text.RegularExpressions;
using System.Windows;
using System.Windows.Controls;
using System.Windows.Data;

namespace Schrabber.Windows
{
	/// <summary>
	/// Window for the user to separate an IInputMedia into IParts.
	/// </summary>
	public partial class SplitWindow : Window
	{

		/// <summary>
		/// IEnumerable of IParts the user separated the IInputmedia into.
		/// </summary>
		public IEnumerable<IPart> Parts
		{
			get => _gridItems.Where(p => !String.IsNullOrWhiteSpace(p.Title)).OrderBy(p => p.Start);
		}

		private readonly IInputMedia _input;
		private readonly ObservableCollection<IPart> _gridItems = new ObservableCollection<IPart>();

		public SplitWindow(IInputMedia input)
		{
			InitializeComponent();

			_input = input;

			#region DataGrid
			Parts_DataGrid.ItemsSource = _gridItems;
			Parts_DataGrid.AutoGeneratedColumns += (object sender, EventArgs e) =>
			{
				// Start
				Parts_DataGrid.Columns[0].Width = 70;
				Parts_DataGrid.Columns[0].SortDirection = ListSortDirection.Ascending;
				// End;
				Parts_DataGrid.Columns[1].Visibility = Visibility.Hidden;
				// Title
				Parts_DataGrid.Columns[2].Width = new DataGridLength(1, DataGridLengthUnitType.Star);
				// Author
				Parts_DataGrid.Columns[3].Width = new DataGridLength(1, DataGridLengthUnitType.Star);

				ICollectionView collectionView = CollectionViewSource.GetDefaultView(Parts_DataGrid.ItemsSource);
				collectionView.SortDescriptions.Clear();
				collectionView.SortDescriptions.Add(new SortDescription((String)Parts_DataGrid.Columns[0].Header, ListSortDirection.Ascending));
			};
			#endregion Datagrid

			_gridItems.Add(Parts.FirstOrDefault() ?? new Part() { Author = input.Author, Title = input.Title, Start = TimeSpan.FromSeconds(0) });
		}

		private void ConfirmButton_Click(object sender, RoutedEventArgs e)
		{
			IPart prev = null;
			foreach (IPart row in _gridItems)
			{
				if (prev != null)
				{
					if (prev.Start == row.Start)
					{
						MessageBox.Show($"Identical timestamp found for: \n \"{prev.Title}\"\n\"{row.Title}\"");

						e.Handled = true;
						return;
					}
					prev.Stop = row.Start;
				}

				prev = row;
			}

			this.DialogResult = true;
			this.Close();
		}

		private void NewPartButton_Click(object sender, RoutedEventArgs e)
		{
			_gridItems.Add(new Part()
			{
				Start = TimeSpan.FromSeconds(0),
			});
		}

		private void ImportPartsButton_Click(object sender, RoutedEventArgs e)
		{
			// TODO: :that:
			MessageBox.Show("Not implemented yet.");
		}
	}
}
